apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-microservico-producao-service
  labels:
    app: tech-challenge-microservico-producao
spec:
  selector:
    app: tech-challenge-microservico-producao
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
